export const BASE_URL = "https://api.themoviedb.org//3/"

export const ACCESS_TOKEN = `eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxNzIyODQwNGIxMGNjOTJmNzAyN2YxZTY3OTY1NWY5MiIsIm5iZiI6MTc0MTY2MjkwMy4xMDksInN1YiI6IjY3Y2ZhYWI3YjVlZTBlMzk3YzYwNzQxYyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.3l78IfVkiHvDAFXIu8RuuyV6w8tjaFnkE-5qanq7_i0`;